SELECT '35Prop' AS 'KODE PROPINSI', 'Kabupaten Situbondo' AS 'KAB-KOTA', '3512037' AS "KODE RS",
  'RS UMUM DAERAH ASEMBAGUS' AS 'NAMA RS',YEAR(kun_tgcheckin) AS 'TAHUN', kit_id AS "NO URUT", kit_kode AS "NO Daftar Terperinci", kit_nama AS "GOLONGAN SEBAB PENYAKIT", 
COUNT(CASE WHEN man_kelamin='L' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 ))<=6 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL UMUR & JSEX_0-<=6hr_L",
COUNT(CASE WHEN man_kelamin='P' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 ))<=6 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL UMUR & JSEX_0-<=6hr_P",
COUNT(CASE WHEN man_kelamin='L' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 )) BETWEEN 7 AND 28 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL UMUR & SEX_>6-<=28hr_L",
COUNT(CASE WHEN man_kelamin='P' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 )) BETWEEN 7 AND 28 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL UMUR & SEX_>6-<=28hr_P",
COUNT(CASE WHEN man_kelamin='L' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 ))>28 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL . UMUR & SEX_>28hr-<=1th_L",
COUNT(CASE WHEN man_kelamin='P' AND (FLOOR( TIMESTAMPDIFF( DAY, man_tglahir, now() ) % 30.4375 ))>28 AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE )<1 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL . UMUR & SEX_>28hr-<=1th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 1 AND 4 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>1-<=4th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 1 AND 4 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>1-<=4th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 5 AND 14 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>4-<=14th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 5 AND 14 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>4-<=14th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 15 AND 24 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>14-<=24th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 15 AND 24 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>14-<=24th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 25 AND 44 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>24-<=44th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 25 AND 44 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>24-<=44th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 45 AND 64 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>44-<=64th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) BETWEEN 45 AND 64 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>44-<=64th_P",
COUNT(CASE WHEN man_kelamin='L' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) >64 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>64th_L",
COUNT(CASE WHEN man_kelamin='P' AND TIMESTAMPDIFF( YEAR, man_tglahir, CURRENT_DATE ) >64 THEN 1 END) AS "JUMLAH PASIEN KASUS MENURUT GOL. UMUR & SEX_>64th_P",
COUNT(CASE WHEN man_kelamin='P' THEN 1 END) AS "KASUS BARU MENURUT JENIS KELAMIN_LK",
COUNT(CASE WHEN man_kelamin='L' THEN 1 END) AS "KASUS BARU MENURUT JENIS KELAMIN_PR", 
COUNT(kpr_kit_id) "JUMLAH KUNJUNGAN" FROM rms_penyakit
LEFT JOIN rms_kunperiksa ON kit_id=kpr_kit_id
LEFT JOIN rms_kunjungan ON kun_id=kpr_kun_id
LEFT JOIN rms_manusia ON man_id=kun_man_id
WHERE kun_tgcheckin BETWEEN '2021-01-01' AND '2022-01-01'
GROUP BY kit_nama
ORDER BY COUNT(kpr_kit_id) DESC