INSERT INTO dks_layanan VALUES(1,'Penyakit Dalam','jatim');
INSERT INTO dks_layanan VALUES(2,'Kesehatan Anak','jatim');
INSERT INTO dks_layanan VALUES(3,'Obstetri','jatim');
INSERT INTO dks_layanan VALUES(4,'Genekologi','jatim');
INSERT INTO dks_layanan VALUES(5,'Bedah','jatim');
INSERT INTO dks_layanan VALUES(6,'Bedah Orthopedi','jatim');
INSERT INTO dks_layanan VALUES(7,'Bedah Saraf','jatim');
INSERT INTO dks_layanan VALUES(8,'Luka Bakar','jatim');
INSERT INTO dks_layanan VALUES(9,'S a r a f','jatim');
INSERT INTO dks_layanan VALUES(10,'J i w a','jatim');
INSERT INTO dks_layanan VALUES(11,'Psikologi','jatim');
INSERT INTO dks_layanan VALUES(12,'Penatalaksana Pnyguna. NAPZA','jatim');
INSERT INTO dks_layanan VALUES(13,'T H T','jatim');
INSERT INTO dks_layanan VALUES(14,'M a t a','jatim');
INSERT INTO dks_layanan VALUES(15,'Kulit & Kelamin','jatim');
INSERT INTO dks_layanan VALUES(16,'Kardiologi','jatim');
INSERT INTO dks_layanan VALUES(17,'Paru-paru','jatim');
INSERT INTO dks_layanan VALUES(18,'Geriatri','jatim');
INSERT INTO dks_layanan VALUES(19,'Radioterapi','jatim');
INSERT INTO dks_layanan VALUES(20,'Kedokteran Nuklir','jatim');
INSERT INTO dks_layanan VALUES(21,'K u s t a','jatim');
INSERT INTO dks_layanan VALUES(22,'Rehabilitasi Medik','jatim');
INSERT INTO dks_layanan VALUES(23,'Isolasi','jatim');
INSERT INTO dks_layanan VALUES(24,'I C U','jatim');
INSERT INTO dks_layanan VALUES(25,'I C C U','jatim');
INSERT INTO dks_layanan VALUES(26,'NICU / PICU','jatim');
INSERT INTO dks_layanan VALUES(27,'Umum','jatim');
INSERT INTO dks_layanan VALUES(28,'Gigi & Mulut','jatim');
INSERT INTO dks_layanan VALUES(29,'Pelayanan Rawat Darurat','jatim');
INSERT INTO dks_layanan VALUES(30,'Perinatologi/Bayi','jatim');
