INSERT INTO dks_tindakan VALUES(1,'Visite Dokter Umum','-','Aktif');
INSERT INTO dks_tindakan VALUES(2,'Visite Dokter Spesialis','-','Aktif');
INSERT INTO dks_tindakan VALUES(3,'On Call Dokter Spesialis','-','Aktif');
INSERT INTO dks_tindakan VALUES(4,'Oral Personal Higiene','-','Aktif');
INSERT INTO dks_tindakan VALUES(5,'Pasang Alat Bantu Nafas Non Invasit','-','Aktif');
INSERT INTO dks_tindakan VALUES(6,'Pasang O2 Support Non Invasit','-','Aktif');
INSERT INTO dks_tindakan VALUES(7,'Suctioning','-','Aktif');
INSERT INTO dks_tindakan VALUES(8,'Koreksi Elektrolit','-','Aktif');
INSERT INTO dks_tindakan VALUES(9,'Pasang kateter Urine','-','Aktif');
INSERT INTO dks_tindakan VALUES(10,'Pasang NGT','-','Aktif');
INSERT INTO dks_tindakan VALUES(11,'Pasang Infus Dengan Paien Syok','-','Aktif');
INSERT INTO dks_tindakan VALUES(12,'Kumbah lambung','-','Aktif');
INSERT INTO dks_tindakan VALUES(13,'Karcis','-','Aktif');
INSERT INTO dks_tindakan VALUES(14,'Akomodasi Makan dan Minum','-','Aktif');
INSERT INTO dks_tindakan VALUES(15,'Injeksi Obat Permacam ( Maksimal 3 )','-','Aktif');
INSERT INTO dks_tindakan VALUES(16,'Koreksi Elektrolit Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(17,'Rekam Medis','-','Aktif');
INSERT INTO dks_tindakan VALUES(18,'Akomodasi dan Makan Minum','-','Aktif');
INSERT INTO dks_tindakan VALUES(19,'Konsultasi Dokter Spesialis','-','Aktif');
INSERT INTO dks_tindakan VALUES(20,'Sampling Vena','-','Aktif');
INSERT INTO dks_tindakan VALUES(21,'On Call Dokter Umum','-','Aktif');
INSERT INTO dks_tindakan VALUES(22,'Nebulisasi Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(23,'Memasang Kateter Urine','-','Aktif');
INSERT INTO dks_tindakan VALUES(24,'Suction Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(25,'Kumbah Lambung Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(26,'Fisioterapi Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(27,'Skin Test Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(28,'Melepas Infus','-','Aktif');
INSERT INTO dks_tindakan VALUES(29,'Mengganti Cairan Infus','-','Aktif');
INSERT INTO dks_tindakan VALUES(30,'Melepas NGT','-','Aktif');
INSERT INTO dks_tindakan VALUES(31,'Spooling Kateter / Infus Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(32,'Regulasi Cepat Insulin Pertindakan','-','Aktif');
INSERT INTO dks_tindakan VALUES(33,'Rawat luka Ringan ( < 10 cm2 )','-','Aktif');
INSERT INTO dks_tindakan VALUES(34,'Memasang NGT','-','Aktif');
INSERT INTO dks_tindakan VALUES(35,'Memasang Infus','-','Aktif');
INSERT INTO dks_tindakan VALUES(36,'Rawat Luka Sedang ( 10 - 20 cm2 )','-','Aktif');
INSERT INTO dks_tindakan VALUES(37,'Resusitasi Cairan','-','Aktif');
INSERT INTO dks_tindakan VALUES(38,'Tindakan Tranfusi','-','Aktif');
INSERT INTO dks_tindakan VALUES(39,'Rawat Luka Berat ( > 20 cm2 )','-','Aktif');
INSERT INTO dks_tindakan VALUES(40,'Oksigen','jam','Aktif');
INSERT INTO dks_tindakan VALUES(41,'Sampling Arteri','-','Aktif');
INSERT INTO dks_tindakan VALUES(42,'Foto Radiologi','-','Aktif');
INSERT INTO dks_tindakan VALUES(43,'Baca Hasil Radiologi','-','Aktif');
INSERT INTO dks_tindakan VALUES(44,'Periksa Darah Lengkap','-','Aktif');
INSERT INTO dks_tindakan VALUES(45,'Pierksa Darah Sedang','-','Aktif');
INSERT INTO dks_tindakan VALUES(46,'Konsultasi Dokter Spesialis Lain','kali','Aktif');
INSERT INTO dks_tindakan VALUES(47,'On Call Spesialis (WA/Telp)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(48,'Pendampingan SC Dokter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(49,'Pembersihan Saluran Nafas','kali','Aktif');
INSERT INTO dks_tindakan VALUES(50,'Ventilasi Manual Bertekan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(51,'Laringoskopi Bayi','Kali','Aktif');
INSERT INTO dks_tindakan VALUES(52,'Suction Meconeum Endo Tracheal Bayi','Kali','Aktif');
INSERT INTO dks_tindakan VALUES(53,'Pemasangan/Pelepasan ETT','kali','Aktif');
INSERT INTO dks_tindakan VALUES(54,'Setting dan Programan Ventilator Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(55,'Keperawatan','-','Aktif');
INSERT INTO dks_tindakan VALUES(56,'Konsul Gizi','-','Aktif');
INSERT INTO dks_tindakan VALUES(57,'Injeksi Obat (Maksimal 3 Obat','Hari','Aktif');
INSERT INTO dks_tindakan VALUES(58,'Tindakan Nebulisasi Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(59,'Tindakan Suction Nebulisasi Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(60,'Tindakan Skin Test Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(61,'Kumbah Lambung Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(62,'Melepas Infus/OBT Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(63,'Spooling Chateter /Infus Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(64,'Memandikan Bayi','Hari','Aktif');
INSERT INTO dks_tindakan VALUES(65,'Memberi Minum Peroral Ke Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(66,'Memantau Syringe/Infus Pump Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(67,'Pemasangan Monitor/Oxymentri','hari','Aktif');
INSERT INTO dks_tindakan VALUES(68,'Rawat Luka <10 cm','2700','Aktif');
INSERT INTO dks_tindakan VALUES(69,'Pemasangan OGT/Maagslang Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(70,'Pengaturan Box Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(71,'Koreksi Elektrolit Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(72,'Pemasanagn Chateter Urine Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(73,'Pemasangan Infus Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(74,'Pemasanagn Incobatori/Infant Warmer','hari','Aktif');
INSERT INTO dks_tindakan VALUES(75,'Pengaturan Fotobtherapy','hari','Aktif');
INSERT INTO dks_tindakan VALUES(76,'Perawatan Jenazah Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(77,'EKG BAyi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(78,'Rawat Luka 10-20 cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(79,'Asistensi SC Perinatologi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(80,'Resusitasi Cairan Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(81,'Tindakan Transfusi Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(82,'Rawat Luka >20cm2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(83,'CVC (dr. Anestesi)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(84,'Vena Sectio','kali','Aktif');
INSERT INTO dks_tindakan VALUES(85,'Umbilical Catheter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(86,'Intra Osseus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(87,'Pasang /Lepas CPAP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(88,'Evaluasi CPAP Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(89,'Pemasangan / Pelepasan Ventilator Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(90,'(Ventilator) Pasang/Lepas Breathing Circuit','hari','Aktif');
INSERT INTO dks_tindakan VALUES(91,'(Ventilator) Evaluasi Breathing Circuit','hari','Aktif');
INSERT INTO dks_tindakan VALUES(92,'Evaluasi Ventilator Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(93,'Observasi Intensif Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(94,'Ob Infus Bayi','hari','Aktif');
INSERT INTO dks_tindakan VALUES(95,'Pemakaian Compresed Air','Jam','Aktif');
INSERT INTO dks_tindakan VALUES(96,'Administrasi','-','Aktif');
INSERT INTO dks_tindakan VALUES(97,'Makmin','hari','Aktif');
INSERT INTO dks_tindakan VALUES(98,'Tindakan Nebulisasi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(99,'Chest Fisioterapi (Clapping)','kali ','Aktif');
INSERT INTO dks_tindakan VALUES(100,'Restrain','kali','Aktif');
INSERT INTO dks_tindakan VALUES(101,'Tindakan Injeksi/Skin Test','kali','Aktif');
INSERT INTO dks_tindakan VALUES(102,'Positioning','kali','Aktif');
INSERT INTO dks_tindakan VALUES(103,'Balans Cairan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(104,'Pasang/Lepas/Evaluasi Syringe Infussion','kali','Aktif');
INSERT INTO dks_tindakan VALUES(105,'Pemberian Nutrisi Personde/Oral/infus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(106,'Cukur Rambut','kali','Aktif');
INSERT INTO dks_tindakan VALUES(107,'Melepas Infus/NGT/chateter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(108,'Regulasi Cepat Insulin','kali','Aktif');
INSERT INTO dks_tindakan VALUES(109,'Pasang Spalk','kali','Aktif');
INSERT INTO dks_tindakan VALUES(110,'Rawat Luka <10 Cm2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(111,'Rawat Luka 10-20 cm2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(112,'Asistensi Tindakan Invasif Dokter','hari','Aktif');
INSERT INTO dks_tindakan VALUES(113,'Pasang/lepas/evaluasi breathing sirkuit','kali','Aktif');
INSERT INTO dks_tindakan VALUES(114,'Pasang/lepas/evaluasi warmer ventilator','kali','Aktif');
INSERT INTO dks_tindakan VALUES(115,'Tindakan transfusi Dewasa','kali','Aktif');
INSERT INTO dks_tindakan VALUES(116,'Pengukuran Invasif Monitoring','kali','Aktif');
INSERT INTO dks_tindakan VALUES(117,'Observasi Instensif','kali','Aktif');
INSERT INTO dks_tindakan VALUES(118,'Ventilasi Manual bertekanan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(119,'Pasang/lepas alat bantu nafas invasif','kali','Aktif');
INSERT INTO dks_tindakan VALUES(120,'Penggunaan Laringoskop','kali','Aktif');
INSERT INTO dks_tindakan VALUES(121,'Pengaturan Ventilator','kali','Aktif');
INSERT INTO dks_tindakan VALUES(122,'Pijat Jantung','kali','Aktif');
INSERT INTO dks_tindakan VALUES(123,'Penggunaan DC chok','hari','Aktif');
INSERT INTO dks_tindakan VALUES(124,'Pemanggilan Tim code blue','kali','Aktif');
INSERT INTO dks_tindakan VALUES(125,'Rawat luka >20 cm2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(126,'observasi intensif','kali','Aktif');
INSERT INTO dks_tindakan VALUES(127,'pemasangan monitoring CVP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(128,'Pasang/lepas/evaluasi ventilator','hari','Aktif');
INSERT INTO dks_tindakan VALUES(129,'Pendampingan/Back up pasien tidak stabil','hari','Aktif');
INSERT INTO dks_tindakan VALUES(130,'ABP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(131,'Punksi Pleura/Ascites','kali','Aktif');
INSERT INTO dks_tindakan VALUES(132,'insersi vena central','kali','Aktif');
INSERT INTO dks_tindakan VALUES(133,'Vena Section','kali','Aktif');
INSERT INTO dks_tindakan VALUES(134,'PDT','kali','Aktif');
INSERT INTO dks_tindakan VALUES(135,'Hemoglobin','-','Aktif');
INSERT INTO dks_tindakan VALUES(136,'leukosit','','Aktif');
INSERT INTO dks_tindakan VALUES(137,'LED (Laju Endap Darah)','','Aktif');
INSERT INTO dks_tindakan VALUES(138,'Hitung jenis','','Aktif');
INSERT INTO dks_tindakan VALUES(139,'PCV(Hematokrit)','','Aktif');
INSERT INTO dks_tindakan VALUES(140,'Trombosit','','Aktif');
INSERT INTO dks_tindakan VALUES(141,'Eritrosit','','Aktif');
INSERT INTO dks_tindakan VALUES(142,'Gol Darah','','Aktif');
INSERT INTO dks_tindakan VALUES(143,'Waktu Pendarahan (BT)','','Aktif');
INSERT INTO dks_tindakan VALUES(144,'Waktu Pembekuan (CT)','','Aktif');
INSERT INTO dks_tindakan VALUES(145,'Mikroskopis Urine ','','Aktif');
INSERT INTO dks_tindakan VALUES(146,'Reduksi Urine','','Aktif');
INSERT INTO dks_tindakan VALUES(147,'Albumin Urine','','Aktif');
INSERT INTO dks_tindakan VALUES(148,'Urobilin Urine','','Aktif');
INSERT INTO dks_tindakan VALUES(149,'Bilirubin urine','','Aktif');
INSERT INTO dks_tindakan VALUES(150,'Sedimen Urine','','Aktif');
INSERT INTO dks_tindakan VALUES(151,'Hapusan Darah','','Aktif');
INSERT INTO dks_tindakan VALUES(152,'Auto Analizer  (Darah Lengkap)','','Aktif');
INSERT INTO dks_tindakan VALUES(153,'Urine Lengkap','','Aktif');
INSERT INTO dks_tindakan VALUES(154,'Alkali Fostase','','Aktif');
INSERT INTO dks_tindakan VALUES(155,'Plano test','','Aktif');
INSERT INTO dks_tindakan VALUES(156,'KOH  (Jamur )','','Aktif');
INSERT INTO dks_tindakan VALUES(157,'GDA','','Aktif');
INSERT INTO dks_tindakan VALUES(158,'BSN (Glukosa Puasa)','','Aktif');
INSERT INTO dks_tindakan VALUES(159,'2JPP','','Aktif');
INSERT INTO dks_tindakan VALUES(160,'SGOT','','Aktif');
INSERT INTO dks_tindakan VALUES(161,'SGPT','','Aktif');
INSERT INTO dks_tindakan VALUES(162,'Bilirubin Total','','Aktif');
INSERT INTO dks_tindakan VALUES(163,'Bilirubin Direct','','Aktif');
INSERT INTO dks_tindakan VALUES(164,'Bilirubin Indirect','','Aktif');
INSERT INTO dks_tindakan VALUES(165,'Total Protein','','Aktif');
INSERT INTO dks_tindakan VALUES(166,'Albumin','','Aktif');
INSERT INTO dks_tindakan VALUES(167,'Globulin ','','Aktif');
INSERT INTO dks_tindakan VALUES(168,'Gamma GT','','Aktif');
INSERT INTO dks_tindakan VALUES(169,'Uric acid','','Aktif');
INSERT INTO dks_tindakan VALUES(170,'Creatinin','','Aktif');
INSERT INTO dks_tindakan VALUES(171,'BUN','','Aktif');
INSERT INTO dks_tindakan VALUES(172,'Ureum','','Aktif');
INSERT INTO dks_tindakan VALUES(173,'Creatinin clearent','','Aktif');
INSERT INTO dks_tindakan VALUES(174,'Urea clearent','','Aktif');
INSERT INTO dks_tindakan VALUES(175,'Cholesterol total','','Aktif');
INSERT INTO dks_tindakan VALUES(176,'Cholesterol HDL','','Aktif');
INSERT INTO dks_tindakan VALUES(177,'Cholesterol LDL','','Aktif');
INSERT INTO dks_tindakan VALUES(178,'Pengecatan gram','','Aktif');
INSERT INTO dks_tindakan VALUES(179,'Sputum BTA 1X','','Aktif');
INSERT INTO dks_tindakan VALUES(180,'Sputum BTA 3X serial','','Aktif');
INSERT INTO dks_tindakan VALUES(181,'Faeces lengkap','','Aktif');
INSERT INTO dks_tindakan VALUES(182,'Secret mata','','Aktif');
INSERT INTO dks_tindakan VALUES(183,'Swab Vagina','','Aktif');
INSERT INTO dks_tindakan VALUES(184,'Neiesser','','Aktif');
INSERT INTO dks_tindakan VALUES(185,'Malaria','','Aktif');
INSERT INTO dks_tindakan VALUES(186,'Kultur urine','','Aktif');
INSERT INTO dks_tindakan VALUES(187,'Dengue blood','','Aktif');
INSERT INTO dks_tindakan VALUES(188,'Narkoba (per 1 macam pemeriksaan )','','Aktif');
INSERT INTO dks_tindakan VALUES(189,'Trigliserida','','Aktif');
INSERT INTO dks_tindakan VALUES(190,'PH','','Aktif');
INSERT INTO dks_tindakan VALUES(191,'Calsium','','Aktif');
INSERT INTO dks_tindakan VALUES(192,'Natrium','','Aktif');
INSERT INTO dks_tindakan VALUES(193,'Kalium','','Aktif');
INSERT INTO dks_tindakan VALUES(194,'Clorida','','Aktif');
INSERT INTO dks_tindakan VALUES(195,'HBs Ag Strip','','Aktif');
INSERT INTO dks_tindakan VALUES(196,'HBs Ab Strip','','Aktif');
INSERT INTO dks_tindakan VALUES(197,'Anti HBs','','Aktif');
INSERT INTO dks_tindakan VALUES(198,'IgM Anti HAV','','Aktif');
INSERT INTO dks_tindakan VALUES(199,'IgM Anti HCV','','Aktif');
INSERT INTO dks_tindakan VALUES(200,'TP HA','','Aktif');
INSERT INTO dks_tindakan VALUES(201,'VDRL','','Aktif');
INSERT INTO dks_tindakan VALUES(202,'Scalling Rahang atas rahang bawah','','Aktif');
INSERT INTO dks_tindakan VALUES(203,'Heating','','Aktif');
INSERT INTO dks_tindakan VALUES(204,'Pengobatan/Kontrol/Pemeriksaan','','Aktif');
INSERT INTO dks_tindakan VALUES(205,'Endodontia (Perawatan/Pengobatan Pupa','','Aktif');
INSERT INTO dks_tindakan VALUES(206,'Bongkar Tumpatan','','Aktif');
INSERT INTO dks_tindakan VALUES(207,'Incisi Abses','','Aktif');
INSERT INTO dks_tindakan VALUES(208,'Buka Jahitan / Jahitan (per)','','Aktif');
INSERT INTO dks_tindakan VALUES(209,'Reposisi TM','','Aktif');
INSERT INTO dks_tindakan VALUES(210,'Grinding / Gigi','','Aktif');
INSERT INTO dks_tindakan VALUES(211,'Curret Per Regio','','Aktif');
INSERT INTO dks_tindakan VALUES(212,'Tumpatan GIC','','Aktif');
INSERT INTO dks_tindakan VALUES(213,'Gingivektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(214,'Bongkar Gigi Tiruan','','Aktif');
INSERT INTO dks_tindakan VALUES(215,'Open Bur','','Aktif');
INSERT INTO dks_tindakan VALUES(216,'Reliefofpain Pulpek','','Aktif');
INSERT INTO dks_tindakan VALUES(217,'Infrared','','Aktif');
INSERT INTO dks_tindakan VALUES(218,'Surat Keterangan Sehat','','Aktif');
INSERT INTO dks_tindakan VALUES(219,'Legalisir 5 Lembar','','Aktif');
INSERT INTO dks_tindakan VALUES(220,'Surat Bebas Narkoba','','Aktif');
INSERT INTO dks_tindakan VALUES(221,'Injeksi Obat Permacam(maksimal 3)','hari','Aktif');
INSERT INTO dks_tindakan VALUES(222,'Spooling kateter/infus pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(223,'Rawat Luka Ringan (10- cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(224,'Memasang Chateter Urine','kali','Aktif');
INSERT INTO dks_tindakan VALUES(225,'Rawat Luka Sedang (10-20 cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(226,'Tindakan Transfusi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(227,'Rawat Luka Berat (>20 cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(228,'Binatu dan Jasa Farmasi','','Aktif');
INSERT INTO dks_tindakan VALUES(229,'Injeksi Obat (maksimal 4 )','-','Aktif');
INSERT INTO dks_tindakan VALUES(230,'Inspekulo','-','Aktif');
INSERT INTO dks_tindakan VALUES(231,'akomodasi','HR','Aktif');
INSERT INTO dks_tindakan VALUES(232,'Injeksi Obat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(233,'Spooling Kateter/ Infus Pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(234,'Rawat Luka Ringan (<10 cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(235,'Binatu dan Jasa Farmasi (jangan digunakan)','','Aktif');
INSERT INTO dks_tindakan VALUES(236,'Akomodasi dan Makan Minum (jangan menggunakan ini)','hari','Aktif');
INSERT INTO dks_tindakan VALUES(237,'Binatu dan Jasa Farmasi (Jangan Menggunakan ini)','','Aktif');
INSERT INTO dks_tindakan VALUES(238,'EKG','','Aktif');
INSERT INTO dks_tindakan VALUES(239,'Injeksi Obat Permacam (maksimal 3)','hari','Aktif');
INSERT INTO dks_tindakan VALUES(240,'Nebulasi Pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(241,'Suctio Pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(242,'Rawat Luka Ringan (<10cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(243,'Karcis (jangan menggunakan tarif ini)','','Aktif');
INSERT INTO dks_tindakan VALUES(244,'On Call Spesialis (WA/TLp)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(245,'Injeksi Obat (Maksimal 4)','hari','Aktif');
INSERT INTO dks_tindakan VALUES(246,'VT (Periksa Dalam)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(247,'Body Hygiene','kali','Aktif');
INSERT INTO dks_tindakan VALUES(248,'Vulva Hygiene Sanitasi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(249,'Perawatan Alat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(250,'Spooling Kateter Infus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(251,'Skiren','kali','Aktif');
INSERT INTO dks_tindakan VALUES(252,'Pemasangan Monitor /Oxymentri','kali','Aktif');
INSERT INTO dks_tindakan VALUES(253,'Rawat Luka <(10-20 cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(254,'Doppler','kali ','Aktif');
INSERT INTO dks_tindakan VALUES(255,'Memasang Melepas Urine','kali','Aktif');
INSERT INTO dks_tindakan VALUES(256,'Memasng NGT','kali','Aktif');
INSERT INTO dks_tindakan VALUES(257,'Memasang Lepas Infus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(258,'Amniotomi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(259,'Episiotomi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(260,'Eksplorasi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(261,'Tindakan Digital','kali','Aktif');
INSERT INTO dks_tindakan VALUES(262,'Perawatan BBL','kali','Aktif');
INSERT INTO dks_tindakan VALUES(263,'USG','Lbr','Aktif');
INSERT INTO dks_tindakan VALUES(264,'CTG','kali','Aktif');
INSERT INTO dks_tindakan VALUES(265,'Hecting Perineum','','Aktif');
INSERT INTO dks_tindakan VALUES(266,'Partus Fisiologi','','Aktif');
INSERT INTO dks_tindakan VALUES(267,'Partus Potologis','','Aktif');
INSERT INTO dks_tindakan VALUES(268,'Forcep Ekstraksi','','Aktif');
INSERT INTO dks_tindakan VALUES(269,'Vakum Ekstrasksi ','','Aktif');
INSERT INTO dks_tindakan VALUES(270,'Hecting Forcio','','Aktif');
INSERT INTO dks_tindakan VALUES(271,'Pasang dan Lepas Kondom Kateter','','Aktif');
INSERT INTO dks_tindakan VALUES(272,'Biopsi Cervik','','Aktif');
INSERT INTO dks_tindakan VALUES(273,'Manual Plasenta','','Aktif');
INSERT INTO dks_tindakan VALUES(274,'Infus Pump/Sienge Pump/Monitor','hari','Aktif');
INSERT INTO dks_tindakan VALUES(275,'Binatu','','Aktif');
INSERT INTO dks_tindakan VALUES(276,'Makan dan Minum','kali','Aktif');
INSERT INTO dks_tindakan VALUES(277,'Jasa Farmasi','','Aktif');
INSERT INTO dks_tindakan VALUES(278,'On Call WA/Telp','','Aktif');
INSERT INTO dks_tindakan VALUES(279,'Body Hygiene (Seka)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(280,'Skin Test Tindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(281,'Memasang Melepas Katater Urine','kali','Aktif');
INSERT INTO dks_tindakan VALUES(282,'Memasang Melepas Infus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(283,'Rawat Luka Berat (.20 cm2)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(284,'Tindikan Digital','kali','Aktif');
INSERT INTO dks_tindakan VALUES(285,'Partus Patologis','','Aktif');
INSERT INTO dks_tindakan VALUES(286,'Forceps Ekstraksi','','Aktif');
INSERT INTO dks_tindakan VALUES(287,'Hecting Forsio','','Aktif');
INSERT INTO dks_tindakan VALUES(288,'On Call Wa/Tlp','','Aktif');
INSERT INTO dks_tindakan VALUES(289,'Pemasangan Monotor/Oxymentri','kali','Aktif');
INSERT INTO dks_tindakan VALUES(290,'Rawat Luka  <10cm2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(291,'Memasang Melepas Kateter Urine','kali','Aktif');
INSERT INTO dks_tindakan VALUES(292,'Amniotkaliomi','kALI','Aktif');
INSERT INTO dks_tindakan VALUES(293,'Peraatan BBL','kali','Aktif');
INSERT INTO dks_tindakan VALUES(294,'Vakum Ekstraksi','','Aktif');
INSERT INTO dks_tindakan VALUES(295,'Pemasanagn Monitor Oxymetri','kali','Aktif');
INSERT INTO dks_tindakan VALUES(296,'Ekplorasi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(297,'perawatan  BBL','kali','Aktif');
INSERT INTO dks_tindakan VALUES(298,'USG tanpa print','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(299,'partus fisoliogi','','Aktif');
INSERT INTO dks_tindakan VALUES(300,'pasang lepas kondom kateter','','Aktif');
INSERT INTO dks_tindakan VALUES(301,'Infus pump/seinge pump/monitor','hari','Aktif');
INSERT INTO dks_tindakan VALUES(302,'adminitrasi','','Aktif');
INSERT INTO dks_tindakan VALUES(303,'makan dan munum','kali','Aktif');
INSERT INTO dks_tindakan VALUES(304,'skin tes pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(305,'Memasng kateter urine','kali','Aktif');
INSERT INTO dks_tindakan VALUES(306,'Jasa Binatu dan Strelisasi Alat (jgan digunakan )','kali','Aktif');
INSERT INTO dks_tindakan VALUES(307,'bintu dan jasa farmasi (jgan menggunakan tarif ini','','Aktif');
INSERT INTO dks_tindakan VALUES(308,'skintest pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(309,'spooling kateter /infus pertindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(310,'Hecting<5','','Aktif');
INSERT INTO dks_tindakan VALUES(311,'Hecting 5-10','','Aktif');
INSERT INTO dks_tindakan VALUES(312,'Hecting 11-20','','Aktif');
INSERT INTO dks_tindakan VALUES(313,'hecting >20','','Aktif');
INSERT INTO dks_tindakan VALUES(314,'skin test','','Aktif');
INSERT INTO dks_tindakan VALUES(315,'Rawat luka ringan','','Aktif');
INSERT INTO dks_tindakan VALUES(316,'rawat luka sedang','','Aktif');
INSERT INTO dks_tindakan VALUES(317,'rawat luka berat','','Aktif');
INSERT INTO dks_tindakan VALUES(318,'nebulizer','','Aktif');
INSERT INTO dks_tindakan VALUES(319,'suction','','Aktif');
INSERT INTO dks_tindakan VALUES(320,'pasang Mayo','','Aktif');
INSERT INTO dks_tindakan VALUES(321,'pasang bidai/gipsum','','Aktif');
INSERT INTO dks_tindakan VALUES(322,'resusitasi','','Aktif');
INSERT INTO dks_tindakan VALUES(323,'kardioversi','','Aktif');
INSERT INTO dks_tindakan VALUES(324,'ekstraksi corpus alienium','','Aktif');
INSERT INTO dks_tindakan VALUES(325,'ekstraksi kuku','','Aktif');
INSERT INTO dks_tindakan VALUES(326,'pasang elastis banded','','Aktif');
INSERT INTO dks_tindakan VALUES(327,'eksisi','','Aktif');
INSERT INTO dks_tindakan VALUES(328,'eksterpasi','','Aktif');
INSERT INTO dks_tindakan VALUES(329,'AFF NGT','','Aktif');
INSERT INTO dks_tindakan VALUES(330,'pasang infus ','','Aktif');
INSERT INTO dks_tindakan VALUES(331,'pasang kateter','','Aktif');
INSERT INTO dks_tindakan VALUES(332,'memasang infus (jangan menggunakan tarif ini)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(333,'injeksi obat permacam  (maksimal 3)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(334,'Rekam Medik','','Aktif');
INSERT INTO dks_tindakan VALUES(335,'Konsultasi Dokter Jaga IGD','','Aktif');
INSERT INTO dks_tindakan VALUES(336,'Widal','-','Aktif');
INSERT INTO dks_tindakan VALUES(337,'Injeksi Obat  (Jangan Menggunakan tarif ini)','kali','Aktif');
INSERT INTO dks_tindakan VALUES(338,'Operasi Jaringan Lunak','-','Aktif');
INSERT INTO dks_tindakan VALUES(339,'Odontektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(340,'Pencabutan dengan CE','','Aktif');
INSERT INTO dks_tindakan VALUES(341,'pencabutan dengankomplikasi','','Aktif');
INSERT INTO dks_tindakan VALUES(342,'Tumpatan sementara','','Aktif');
INSERT INTO dks_tindakan VALUES(343,'Tumpatan Komposit','','Aktif');
INSERT INTO dks_tindakan VALUES(344,'Pencabutan','','Aktif');
INSERT INTO dks_tindakan VALUES(345,'Perawatn Endo','','Aktif');
INSERT INTO dks_tindakan VALUES(346,'Pemasangan Monitor Oxymetri','','Aktif');
INSERT INTO dks_tindakan VALUES(347,'Bidai Kaki','','Aktif');
INSERT INTO dks_tindakan VALUES(348,'Bidai Tangan','','Aktif');
INSERT INTO dks_tindakan VALUES(349,'Dr Spesialis onsite','-','Aktif');
INSERT INTO dks_tindakan VALUES(350,'Oksigen  /jam','jam','Aktif');
INSERT INTO dks_tindakan VALUES(351,'ganti cairan','-','Aktif');
INSERT INTO dks_tindakan VALUES(352,'Visum Hidup/Asuransi','','Aktif');
INSERT INTO dks_tindakan VALUES(353,'Visum Jenazah Resiko','','Aktif');
INSERT INTO dks_tindakan VALUES(354,'Visum Jenazah Tanpa Resiko','','Aktif');
INSERT INTO dks_tindakan VALUES(355,'Konsul Antar Spesialis','','Aktif');
INSERT INTO dks_tindakan VALUES(356,'USG 4 DImensi Non Cetak','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(357,'TCM','','Aktif');
INSERT INTO dks_tindakan VALUES(358,'BGA','','Aktif');
INSERT INTO dks_tindakan VALUES(359,'Jasa Binatu dan Strelisasi Alat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(360,'Jasa Binatu dan Strelisasi Alat (jangan digunakan)','','Aktif');
INSERT INTO dks_tindakan VALUES(361,'Jasa Binatu dan Strelisasi Alat (jangn digunakan)','','Aktif');
INSERT INTO dks_tindakan VALUES(362,'Pemeriksaan Rhesus','-','Aktif');
INSERT INTO dks_tindakan VALUES(363,'Pemeriksaan NS1','-','Aktif');
INSERT INTO dks_tindakan VALUES(364,'Surat Kematian','-','Aktif');
INSERT INTO dks_tindakan VALUES(365,'on call dr spesialis IGD','-','Aktif');
INSERT INTO dks_tindakan VALUES(366,'Transfusi Darah (PMI)','ktg','Aktif');
INSERT INTO dks_tindakan VALUES(367,'WT','','Aktif');
INSERT INTO dks_tindakan VALUES(368,'AF Jahitan','','Aktif');
INSERT INTO dks_tindakan VALUES(369,'AF Kateter','','Aktif');
INSERT INTO dks_tindakan VALUES(370,'Circumisi','','Aktif');
INSERT INTO dks_tindakan VALUES(371,'Incici','','Aktif');
INSERT INTO dks_tindakan VALUES(372,'Pasang Chateter','','Aktif');
INSERT INTO dks_tindakan VALUES(373,'Lepas Chateter','','Aktif');
INSERT INTO dks_tindakan VALUES(374,'Sirkumsisi Dengan LA','','Aktif');
INSERT INTO dks_tindakan VALUES(375,'Atherum kecil dg tindakan ekslirpasi','','Aktif');
INSERT INTO dks_tindakan VALUES(376,'Eksisi tahi lalat kecil','','Aktif');
INSERT INTO dks_tindakan VALUES(377,'Lipoma tindakan eksisi (kecil)','','Aktif');
INSERT INTO dks_tindakan VALUES(378,'Prosedur tindakan Vulnus Morsum','','Aktif');
INSERT INTO dks_tindakan VALUES(379,'Prosedur tind vulnus ictum/vulnus puctum','','Aktif');
INSERT INTO dks_tindakan VALUES(380,'Prosedur tindakan mucocelle eksisi','','Aktif');
INSERT INTO dks_tindakan VALUES(381,'Prosedur tindakan vulnus apertum','','Aktif');
INSERT INTO dks_tindakan VALUES(382,'Prosedur tindakan eksis clavus','','Aktif');
INSERT INTO dks_tindakan VALUES(383,'Sectio Cesare Kelas 3','','Aktif');
INSERT INTO dks_tindakan VALUES(384,'Sectio Cesare Kelas 2','','Aktif');
INSERT INTO dks_tindakan VALUES(385,'Sectio Cesare Kelas 1','','Aktif');
INSERT INTO dks_tindakan VALUES(386,'Sectio Cesare VIP','','Aktif');
INSERT INTO dks_tindakan VALUES(387,'Histerectomy','','Aktif');
INSERT INTO dks_tindakan VALUES(388,'Myomectomy','','Aktif');
INSERT INTO dks_tindakan VALUES(389,'Cystectomy','','Aktif');
INSERT INTO dks_tindakan VALUES(390,'Curretage','','Aktif');
INSERT INTO dks_tindakan VALUES(391,'Perawatan Jenazah Tanpa Resiko','','Aktif');
INSERT INTO dks_tindakan VALUES(392,'Perawatan Jenazah Resiko','','Aktif');
INSERT INTO dks_tindakan VALUES(393,'Jasa Binatu/Strelisasi Alat','','Aktif');
INSERT INTO dks_tindakan VALUES(394,'Jasa Binatu/Strelisasi Alat (jangan digunakan)','','Aktif');
INSERT INTO dks_tindakan VALUES(395,'Hba1c','','Aktif');
INSERT INTO dks_tindakan VALUES(396,'Rapid HIV','','Aktif');
INSERT INTO dks_tindakan VALUES(397,'Konsultasi Spesialis Lain','','Aktif');
INSERT INTO dks_tindakan VALUES(398,'On Call Spesialis','','Aktif');
INSERT INTO dks_tindakan VALUES(399,'Setting dan Pemrograman Ventilator Bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(400,'Tindakan Skin test','','Aktif');
INSERT INTO dks_tindakan VALUES(401,'Spooling kateter/Infus bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(402,'Rwat luka <10 cm','','Aktif');
INSERT INTO dks_tindakan VALUES(403,'Pemasangan OGT/ Maagslang bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(404,'pemasanagn kateter  urine bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(405,'pemasangan incobatori/infant warmer','hari','Aktif');
INSERT INTO dks_tindakan VALUES(406,'Umbilical Chateter','','Aktif');
INSERT INTO dks_tindakan VALUES(407,'Inta Osseus','','Aktif');
INSERT INTO dks_tindakan VALUES(408,'Pasang/Lepas CPAP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(409,'Pemasangan/pelepasan ventilator Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(410,'Pasang /lepas Breathing Circuit','kali','Aktif');
INSERT INTO dks_tindakan VALUES(411,'Evaluasi Breathing Circuit','kali','Aktif');
INSERT INTO dks_tindakan VALUES(412,'(Ventilator) Observasi Intensif bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(413,'Balance Cairan','','Aktif');
INSERT INTO dks_tindakan VALUES(414,'Suction Meconeum Endo Trachel Bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(415,'memantau syringe / infus pupm bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(416,'Rawat luka<10 cm','','Aktif');
INSERT INTO dks_tindakan VALUES(417,'Pemasangan kateter Urine Bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(418,'Pemasangan incubatori/infant warmer','','Aktif');
INSERT INTO dks_tindakan VALUES(419,'Tindaka Transfusi Bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(420,'Umblical Chateter','','Aktif');
INSERT INTO dks_tindakan VALUES(421,'Pasang/Lepas Braething Circuit','','Aktif');
INSERT INTO dks_tindakan VALUES(422,'Melepas infus/ OBT bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(423,'Spooling kateter/ infus bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(424,'Memberi Minum Peroral bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(425,'Memantau Syringe/ infus pump bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(426,'Umbilcal Chateter','','Aktif');
INSERT INTO dks_tindakan VALUES(427,'Pemasangan /Pelepasan Ventilator bayi','','Aktif');
INSERT INTO dks_tindakan VALUES(428,'Pasang lepas Breathing Circuit','','Aktif');
INSERT INTO dks_tindakan VALUES(429,'Eksisi Dengan GA (kecil)','','Aktif');
INSERT INTO dks_tindakan VALUES(430,'Eksisi Dengan GA (Sedang)','','Aktif');
INSERT INTO dks_tindakan VALUES(431,'Eksisi Dengan GA (Besar/Penyulit)','','Aktif');
INSERT INTO dks_tindakan VALUES(432,'Sirkumsisi (Lokal Anestesi)','','Aktif');
INSERT INTO dks_tindakan VALUES(433,'Sirkumsi (General Anestesi)','','Aktif');
INSERT INTO dks_tindakan VALUES(434,'Eksisi dengan LA (kecil)','','Aktif');
INSERT INTO dks_tindakan VALUES(435,'Eksisi dengan LA (Sedang)','','Aktif');
INSERT INTO dks_tindakan VALUES(436,'Eksisi dengan LA (Besar)','','Aktif');
INSERT INTO dks_tindakan VALUES(437,'Mastektomi Simpel','','Aktif');
INSERT INTO dks_tindakan VALUES(438,'Diseksi Aksila','','Aktif');
INSERT INTO dks_tindakan VALUES(439,'Isthmolobektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(440,'Subtotal Lobektomi Unilateral','','Aktif');
INSERT INTO dks_tindakan VALUES(441,'Fistulotomy','','Aktif');
INSERT INTO dks_tindakan VALUES(442,'Insisi Drainase Abses degan GA (Sedang)','','Aktif');
INSERT INTO dks_tindakan VALUES(443,'Insisi Drainase Abses degan GA (Besar)','','Aktif');
INSERT INTO dks_tindakan VALUES(444,'Hemorrhoidektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(445,'Herniotomi','','Aktif');
INSERT INTO dks_tindakan VALUES(446,'Appendektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(447,'Laparotomi Eksplorasi','','Aktif');
INSERT INTO dks_tindakan VALUES(448,'Reseksi usus Anastomosis','','Aktif');
INSERT INTO dks_tindakan VALUES(449,'Stoma','','Aktif');
INSERT INTO dks_tindakan VALUES(450,'Packing Hepar','','Aktif');
INSERT INTO dks_tindakan VALUES(451,'Kolesistektomi','','Aktif');
INSERT INTO dks_tindakan VALUES(452,'Sistostomi','','Aktif');
INSERT INTO dks_tindakan VALUES(453,'Eksisi Biopsi GA','','Aktif');
INSERT INTO dks_tindakan VALUES(454,'Eksisi Biopsi LA','','Aktif');
INSERT INTO dks_tindakan VALUES(455,'Insisi Biopsi (LA)','','Aktif');
INSERT INTO dks_tindakan VALUES(456,'Amputasi Digiti   Debridement','','Aktif');
INSERT INTO dks_tindakan VALUES(457,'Lipoma tindakan eksisi LA (Sedang)','','Aktif');
INSERT INTO dks_tindakan VALUES(458,'Pasang Monitor/ Oxymetri Dewasa','','Aktif');
INSERT INTO dks_tindakan VALUES(459,'Pasang /Lepas/Evaluasi Syringe Infussion Pump ','','Aktif');
INSERT INTO dks_tindakan VALUES(460,'Melapas Infus/NGT/Kateter','','Aktif');
INSERT INTO dks_tindakan VALUES(461,'Pasang Infus dengan Pasien Syok','','Aktif');
INSERT INTO dks_tindakan VALUES(462,'Asisntensi Tindakan Invasif Dokter','','Aktif');
INSERT INTO dks_tindakan VALUES(463,'Pasang /Lepas Alat bantu nafas invasif','','Aktif');
INSERT INTO dks_tindakan VALUES(464,'Penggunaan DC Shok','','Aktif');
INSERT INTO dks_tindakan VALUES(465,'Pemasangan Monitor CVP','','Aktif');
INSERT INTO dks_tindakan VALUES(466,'Pendampingna /Back Up Pasien tidak stabil','','Aktif');
INSERT INTO dks_tindakan VALUES(467,'Punksi Pluera/Ascites','','Aktif');
INSERT INTO dks_tindakan VALUES(468,'oral Personal Higinie','kali','Aktif');
INSERT INTO dks_tindakan VALUES(469,'Pasang Monitor/Oxymetri Dewasa','hari','Aktif');
INSERT INTO dks_tindakan VALUES(470,'Pasang/lepas/Evaluasi Syringe Infussion Pump','','Aktif');
INSERT INTO dks_tindakan VALUES(471,'Jasa Binatu/ Streliasasi Alat','','Aktif');
INSERT INTO dks_tindakan VALUES(472,'Visite bersama Dokter Spesialis','','Aktif');
INSERT INTO dks_tindakan VALUES(473,'Konsultasi Dokter Spesialis On Call','kali','Aktif');
INSERT INTO dks_tindakan VALUES(474,'Konsultasi Antar Poli','','Aktif');
INSERT INTO dks_tindakan VALUES(475,'VT','','Aktif');
INSERT INTO dks_tindakan VALUES(476,'Vulva Hygiene','kali','Aktif');
INSERT INTO dks_tindakan VALUES(477,'Nutrisi/Sonde','','Aktif');
INSERT INTO dks_tindakan VALUES(478,'Personal Hygiene','kali','Aktif');
INSERT INTO dks_tindakan VALUES(479,'Pasang Lepas O2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(480,'Pemasangan Restrain','kali','Aktif');
INSERT INTO dks_tindakan VALUES(481,'Claping','kali','Aktif');
INSERT INTO dks_tindakan VALUES(482,'Spooling  Kateter/Infus Tindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(483,'Infus Pump','kali','Aktif');
INSERT INTO dks_tindakan VALUES(484,'Syring/Infus Pump','kali','Aktif');
INSERT INTO dks_tindakan VALUES(485,'Monitor','kali','Aktif');
INSERT INTO dks_tindakan VALUES(486,'Inkubator','kali','Aktif');
INSERT INTO dks_tindakan VALUES(487,'Infanwarmer','kali','Aktif');
INSERT INTO dks_tindakan VALUES(488,'NST','kali','Aktif');
INSERT INTO dks_tindakan VALUES(489,'Foto Terapi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(490,'Pasang Lepas Kateter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(491,'NGT/OGT','kali','Aktif');
INSERT INTO dks_tindakan VALUES(492,'Pasang Bidai','kali','Aktif');
INSERT INTO dks_tindakan VALUES(493,'Pasang Lepas CPAAP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(494,'Asistensi Invasif Dokter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(495,'Perawatan Jenazah','kali','Aktif');
INSERT INTO dks_tindakan VALUES(496,'Jahit Luka Sederhana','kali','Aktif');
INSERT INTO dks_tindakan VALUES(497,'Resusitasi Dewasa','kali','Aktif');
INSERT INTO dks_tindakan VALUES(498,'Resusitasi Bayi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(499,'Pasang Alat Bantu Invasife','kali','Aktif');
INSERT INTO dks_tindakan VALUES(500,'Lepas alat Bantu Invasife','kali','Aktif');
INSERT INTO dks_tindakan VALUES(501,'Observasi Pasien Intensife','kali','Aktif');
INSERT INTO dks_tindakan VALUES(502,'DC Shok','kali','Aktif');
INSERT INTO dks_tindakan VALUES(503,'Evaluasi Ventilator','kali','Aktif');
INSERT INTO dks_tindakan VALUES(504,'Pendampingan /Backup Pasien tidak Stabil','kali','Aktif');
INSERT INTO dks_tindakan VALUES(505,'Rawat Luka >20 cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(506,'Evaluasi CPAAP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(507,'Suction Endotrakeal Mekonial','kali','Aktif');
INSERT INTO dks_tindakan VALUES(508,'Monitoring CVP','kali','Aktif');
INSERT INTO dks_tindakan VALUES(509,'Pendampingan SC','kali','Aktif');
INSERT INTO dks_tindakan VALUES(510,'Heacting Perineum Derajat 1-2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(511,'Digital','kali','Aktif');
INSERT INTO dks_tindakan VALUES(512,'Intra Osesus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(513,'Pungsi Pleura/Asites','kali','Aktif');
INSERT INTO dks_tindakan VALUES(514,'Plasenta Manual','kali','Aktif');
INSERT INTO dks_tindakan VALUES(515,'Heacting Partio','kali','Aktif');
INSERT INTO dks_tindakan VALUES(516,'Pasang Buka Implant','kali','Aktif');
INSERT INTO dks_tindakan VALUES(517,'Pasang Buka IUD','kali','Aktif');
INSERT INTO dks_tindakan VALUES(518,'KBI/KBE','kali','Aktif');
INSERT INTO dks_tindakan VALUES(519,'Jahit Luka >10 cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(520,'Sircumsisi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(521,'Partus Dengan Penyulit','kali','Aktif');
INSERT INTO dks_tindakan VALUES(522,'Vena Seksi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(523,'CVC','kali','Aktif');
INSERT INTO dks_tindakan VALUES(524,'Curatage','kali','Aktif');
INSERT INTO dks_tindakan VALUES(525,'Marsuoialisasi Abses Bhartolini','kali','Aktif');
INSERT INTO dks_tindakan VALUES(526,'Repair Robekan Vagina','kali','Aktif');
INSERT INTO dks_tindakan VALUES(527,'Laparatomy','kali','Aktif');
INSERT INTO dks_tindakan VALUES(528,'SC','','Aktif');
INSERT INTO dks_tindakan VALUES(529,'Tracheostomy','kali','Aktif');
INSERT INTO dks_tindakan VALUES(530,'Jasa Binatu dan Strealisasi Alat','','Aktif');
INSERT INTO dks_tindakan VALUES(531,'Jasa Keperawatan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(532,'Doopler','kali','Aktif');
INSERT INTO dks_tindakan VALUES(533,'Spooling kateter/Infus Tindakan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(534,'Asistensi Invasife Dokter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(535,'Pemanggilan Time Code blue','kali','Aktif');
INSERT INTO dks_tindakan VALUES(536,'Intra Oesus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(537,'Heacting portio','kali','Aktif');
INSERT INTO dks_tindakan VALUES(538,'Jahit luka >10cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(539,'Circumsisi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(540,'Umbilikal Kateter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(541,'Marsupialisasi Abses Bhartolini','kali','Aktif');
INSERT INTO dks_tindakan VALUES(542,'Konsul dokter spesialis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(543,'Balnce Cairan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(544,'Rawat Luka >20cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(545,'Heatcting perinium derajat 1-2','kali','Aktif');
INSERT INTO dks_tindakan VALUES(546,'Pungsi pleura /asites','kali','Aktif');
INSERT INTO dks_tindakan VALUES(547,'Curatege','kali','Aktif');
INSERT INTO dks_tindakan VALUES(548,'Marsupialisasi Abses Bhartoloni','kali','Aktif');
INSERT INTO dks_tindakan VALUES(549,'pasang lepas 02','kali','Aktif');
INSERT INTO dks_tindakan VALUES(550,'Rawat luka 10-20cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(551,'lepas alat bamntu invasife','kali','Aktif');
INSERT INTO dks_tindakan VALUES(552,'viste bersama dokter spesialis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(553,'DC shock','kali','Aktif');
INSERT INTO dks_tindakan VALUES(554,'Rawat luka >20 vm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(555,'Episotomi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(556,'Jahit luka > 10cm','kali','Aktif');
INSERT INTO dks_tindakan VALUES(557,'Perawatan jenazah dengan resiko','kali','Aktif');
INSERT INTO dks_tindakan VALUES(558,'Pemakaian kmar jenazah','kali','Aktif');
INSERT INTO dks_tindakan VALUES(559,'Pengawetan jenazah','kali','Aktif');
INSERT INTO dks_tindakan VALUES(560,'Bedah Jenazah','kali','Aktif');
INSERT INTO dks_tindakan VALUES(561,'Penyimpanan Jenazah','hari','Aktif');
INSERT INTO dks_tindakan VALUES(562,'Bedah jenazah yang digali dari kubur','kali','Aktif');
INSERT INTO dks_tindakan VALUES(563,'Rawat Observasi (<6 jam) singel tarif','kali','Aktif');
INSERT INTO dks_tindakan VALUES(564,'Rawat Observasi Dokter Spesialis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(565,'Konsultasi Dokter Jaga','kali','Aktif');
INSERT INTO dks_tindakan VALUES(566,'Visum','kali','Aktif');
INSERT INTO dks_tindakan VALUES(567,'USG Dengan Print','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(568,'USG Jantung','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(569,'USG tanap print','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(570,'USG 3 Dimensi non cetak','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(571,'USG 3 Dimensi   Cetak','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(572,'USG 4 Dimensi  Cetak','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(573,'Foto Rongent Film Kecil 14/24 24/30','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(574,'Foto rongent film besar 30/40 35/43','lbr','Aktif');
INSERT INTO dks_tindakan VALUES(575,'Konsultasi Dokter Spesialis on Site','kali','Aktif');
INSERT INTO dks_tindakan VALUES(576,'OGT Anak','kali','Aktif');
INSERT INTO dks_tindakan VALUES(577,'Pasang infung dengan pasien Syok','kali','Aktif');
INSERT INTO dks_tindakan VALUES(578,'Pasang /lepas/Evaluasi Breathing Sirkuit','kali','Aktif');
INSERT INTO dks_tindakan VALUES(579,'Tindakan Tranfusi Dewasa','kali','Aktif');
INSERT INTO dks_tindakan VALUES(580,'Penggunaan DC Chock','kali','Aktif');
INSERT INTO dks_tindakan VALUES(581,'Pendampingan / Back Up pasien tidak stabil','kali','Aktif');
INSERT INTO dks_tindakan VALUES(582,'Tindkan Injeksi/ Skin test','kali','Aktif');
INSERT INTO dks_tindakan VALUES(583,'Melepas Infus/NGT/Kateter','kali','Aktif');
INSERT INTO dks_tindakan VALUES(584,'Observasi Isntensif','kali','Aktif');
INSERT INTO dks_tindakan VALUES(585,'Pemasanangan Monitor CVp','kali','Aktif');
INSERT INTO dks_tindakan VALUES(586,'Pendampingan /Back Up Pasien Tidak stabil','kali','Aktif');
INSERT INTO dks_tindakan VALUES(587,'Tindakan SC Dokter Spesialis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(588,'Asistensi Bedah','kali','Aktif');
INSERT INTO dks_tindakan VALUES(589,'Asistensi Anestesi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(590,'Asistensi Instrumentasi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(591,'Monitoring','kali','Aktif');
INSERT INTO dks_tindakan VALUES(592,'Skin Reparation','kali','Aktif');
INSERT INTO dks_tindakan VALUES(593,'Unlop','kali','Aktif');
INSERT INTO dks_tindakan VALUES(594,'Suction Anestesi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(595,'Injeksi','kali','Aktif');
INSERT INTO dks_tindakan VALUES(596,'Drapping','kali','Aktif');
INSERT INTO dks_tindakan VALUES(597,'Streliasasi Alat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(598,'Tindakan Dokter Spesialis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(599,'Asistensi Instrument','kali','Aktif');
INSERT INTO dks_tindakan VALUES(600,'Skin Preparation','kali','Aktif');
INSERT INTO dks_tindakan VALUES(601,'Strerilisasi Alat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(602,'Sterliasasi Alat','kali','Aktif');
INSERT INTO dks_tindakan VALUES(603,'Jasa Binatu','kg','Aktif');
INSERT INTO dks_tindakan VALUES(604,'Pelayanan Binatu','kg','Aktif');
INSERT INTO dks_tindakan VALUES(605,'Sterilisasi Set Alat','set','Aktif');
INSERT INTO dks_tindakan VALUES(606,'Repair Jahitan','kali','Aktif');
INSERT INTO dks_tindakan VALUES(607,'Eksisi FAM dengan GA','','Aktif');
INSERT INTO dks_tindakan VALUES(608,'Eksisi FAM dengan GA (besar/penyulit/bilateral)','','Aktif');
INSERT INTO dks_tindakan VALUES(609,'Debridement','','Aktif');
INSERT INTO dks_tindakan VALUES(610,'Trakeostomi','','Aktif');
INSERT INTO dks_tindakan VALUES(611,'Pasang lepas rol tampon','','Aktif');
INSERT INTO dks_tindakan VALUES(612,'Pasang Lepas Tampon','','Aktif');
INSERT INTO dks_tindakan VALUES(613,'Papsmear','-','Aktif');
INSERT INTO dks_tindakan VALUES(614,'Pasang/Lepas IUD','-','Aktif');
INSERT INTO dks_tindakan VALUES(615,'NST/CTG','-','Aktif');
INSERT INTO dks_tindakan VALUES(616,'Rawat Luka','-','Aktif');
INSERT INTO dks_tindakan VALUES(617,'TVS USG','-','Aktif');
INSERT INTO dks_tindakan VALUES(618,'Slit Lamp','kali','Aktif');
INSERT INTO dks_tindakan VALUES(619,'Auto Ref   Visus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(620,'Fundus','kali','Aktif');
INSERT INTO dks_tindakan VALUES(621,'T.I.O','kali','Aktif');
INSERT INTO dks_tindakan VALUES(622,'Tindakan Trikiasis','kali','Aktif');
INSERT INTO dks_tindakan VALUES(623,'Ixci Chalazion','kali','Aktif');
INSERT INTO dks_tindakan VALUES(624,'Ixici Pteregium','kali','Aktif');
INSERT INTO dks_tindakan VALUES(625,'CLG Pteregium','kali','Aktif');
INSERT INTO dks_tindakan VALUES(626,'Katarak  IOL','kali','Aktif');
INSERT INTO dks_tindakan VALUES(627,'Nebul   Suction','kali','Aktif');
INSERT INTO dks_tindakan VALUES(628,'Pasang Monitor / Oxymetri Dewasa','','Aktif');
INSERT INTO dks_tindakan VALUES(629,'Transfusi TC (PMI)','ktg','Aktif');
INSERT INTO dks_tindakan VALUES(630,'USG ABDOMEN','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(631,'KONSUL USG KELAS 1','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(632,'KONSUL USG KELAS II','','Aktif');
INSERT INTO dks_tindakan VALUES(633,'KONSUL USG KELAS III','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(634,'KONSUL USG VIP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(635,'KONSUL USG POLI/KLINIK','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(636,'KONSUL USG KELAS I','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(637,'KONSUL USG KELAS VIP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(638,'FILM 24X30 (S) KELAS I','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(639,'FILM 24X30 (S) KELAS II','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(640,'FILM 24X30 (S) KELAS III','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(641,'FILM 24X30 (S) KELAS VIP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(642,'FILM 24X30 (S) POLI/KLINIK','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(643,'FILM 24X30/30X40 M/L KELAS I','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(644,'FILM 24X30/30X40 M/L KELAS II','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(645,'FILM 24X30/30X40 M/L KELAS III','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(646,'FILM 24X30/30X40 M/L KELAS VIP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(647,'FILM 24X30 (S)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(648,'FILM 24X30/30X40 (M/L) ','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(649,'KONSUL FOTO KELAS I','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(650,'KONSUL FOTO KELAS II','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(651,'KONSUL FOTO KELAS III','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(652,'KONSUL FOTO KELAS VIP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(653,'KONSUL FOTO POLI/KLINIK','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(654,'ADMINISTRASI PASIEN RAWAT INAP','','Aktif');
INSERT INTO dks_tindakan VALUES(655,'VISITE DOKTER BERSAMA DOKTER SPESIALIS','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(656,'STERIALISASI TIAP SET ALAT','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(657,'PELAYANAN BINATU TIAP KG','kg','Aktif');
INSERT INTO dks_tindakan VALUES(658,'INJEKSI OBAT PERMACAM(MAX 3)','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(659,'KOREKSI ELEKTRONIK PERTINDAKAN','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(660,'NEBULISASI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(661,'FISIOTERAPI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(662,'SPOOLING KATETER/INFUS','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(663,'RAWAT LUKA RINGAN (10 -CM2)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(664,'RAWAT LUKA (10-20 CM2)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(665,'OKSIGEN PERJAM','JAM','Aktif');
INSERT INTO dks_tindakan VALUES(666,'OKSIGEN PERTABUNG','TBG','Aktif');
INSERT INTO dks_tindakan VALUES(667,'STERELIASASI TIAP SET ALAT','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(668,'INJEKSI OBAT (MAX 3)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(669,'SPOOLING KATHETER/INFUS','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(670,'RAWAT LUKA RINGAN (<10 CM)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(671,'MEMASANG KHATETER URINE','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(672,'RAWAT LUKA (>20 CM2)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(673,'SPOOLING KHATETER/INFUS','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(674,' MEMASANG INFUS','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(675,'ORAL PERSONAL HIGINE','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(676,'KOREKSI ELEKTRONIK','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(677,'PASANG/LEPAS/EVALUASI BREATHING','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(678,'PENGGUNAAN LARINGSKOP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(679,'OBSERVASIF INTENSIF','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(680,'PENDAMPINGAN/ BACK UP PASIEN TIDAK STABIL','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(681,'PASANG O2 SUPPORT NON INVASIT`','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(682,'ECG/EKG','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(683,'PASANG MONITOR','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(684,'MANDIKAN BAYI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(685,'PASANG OGT/MAAGSLANG','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(686,'PENGATURAN BOX','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(687,'PASANG INCUBATOR/INFANT WARMER','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(688,'LARINGOSKOP BAYI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(689,'PASANG/LEPAS ETT','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(690,'SETTING/PROGRAM VENTILATOR BAYI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(691,'CVC (DR. ANESTESI )','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(692,'PASANG/LEPAS/CPAP BAYI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(693,'PASANG/LEPAS VENTILATOR','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(694,'PASANG/LEPAS BREATHING CIRCUIT','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(695,'TRANSFUSI DARAH','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(696,' VISITE DOKTER UMUM','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(697,'PERIKSA DALAM (VT)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(698,'PASANG LEPAS TEMPON','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(699,'PERATAAN BBL','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(700,'PASANG/LEPAS KONDOM CHATETER','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(701,'HECTING PERENEUM','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(702,'HECTING  <5','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(703,'RAWAT LUKA BESAR','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(704,'EKTRAKSI CORPUS ALIENIUM','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(705,'EKTRAKSI KUKU','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(706,'INJEKSI OBAT`','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(707,'KARCIS HARIAN (umum)','','Aktif');
INSERT INTO dks_tindakan VALUES(708,'RAWAT OBS (<6 JAM) DOKTER UMUM (SINGLE TARIF)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(709,'KEPERAWATAN (UMUM)','','Aktif');
INSERT INTO dks_tindakan VALUES(710,'KONSULTASI DOKTER JAGA IGD UTK RAJAL/RANAP (UMUM)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(711,'KEPERWATAN (GAKIN)','','Aktif');
INSERT INTO dks_tindakan VALUES(712,'KONSUL DOKTER JAGA IGD TK RAJAL/RANAP (GAKIN)','','Aktif');
INSERT INTO dks_tindakan VALUES(713,'HECTING  <5 (JENAZAH)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(714,'HECTING  5-10 (JENAZAH)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(715,'HECTING  11-20 (JENAZAH)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(716,'HECTING  >20 (JENAZAH)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(717,'PEMAKAIAN KAMR JENAZAH','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(718,'PENYIMPANAN JENAZAH PERHARI','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(719,'BEDAH JENAZAH YANG DI GALI DIKUBUR','','Aktif');
INSERT INTO dks_tindakan VALUES(720,'OTOPSI JENAZAH/VISUM ET REPERTUM','','Aktif');
INSERT INTO dks_tindakan VALUES(721,'VISUM KORBAN HIDUP','','Aktif');
INSERT INTO dks_tindakan VALUES(722,'PCV (HEMATOKRIT)','','Aktif');
INSERT INTO dks_tindakan VALUES(723,'AUTO ANALIZER (DARAH LENGKAP)','','Aktif');
INSERT INTO dks_tindakan VALUES(724,'SPUTUM BTA 3X SEREAL','','Aktif');
INSERT INTO dks_tindakan VALUES(725,'NEISSER','','Aktif');
INSERT INTO dks_tindakan VALUES(726,'NARKOBA(PER 1 MCM PMR)','','Aktif');
INSERT INTO dks_tindakan VALUES(727,'MAGNESIUM','','Aktif');
INSERT INTO dks_tindakan VALUES(728,'HBS AG STREP ','','Aktif');
INSERT INTO dks_tindakan VALUES(729,'HBS AB STREP','','Aktif');
INSERT INTO dks_tindakan VALUES(730,'HIV','','Aktif');
INSERT INTO dks_tindakan VALUES(731,'ELEKTROLIT','','Aktif');
INSERT INTO dks_tindakan VALUES(732,'URINE LENGKAP   SEDIMEN','','Aktif');
INSERT INTO dks_tindakan VALUES(733,'PENGOBATAN KERADANGAN / MEDIKASI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(734,'PENCABUTAN GIGI SULUNG','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(735,'PENCABUTAN GIGI TETAP','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(736,'PENCABUTAN GIGI TETAP DANGAN PENYULIT / KOMPLIKASI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(737,'MAKANAN DIET SONDE','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(738,'TUMPATAN SEMENTARA DENAN MEDIKAMENT','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(739,'PULP. CAPPING','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(740,'MAKANAN DIET DM','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(741,'MAKANAN DIET RENDAH GARAM','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(742,'MAKANAN DIET JANTUNG','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(743,'MAKANAN DIET TKTP','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(744,'ENDODONTIK SALURAN AKAR TUNGGAL','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(745,'MAKANAN NON DIET','HARI','Aktif');
INSERT INTO dks_tindakan VALUES(746,'ENDODONTIK SALURAN AKAR LEBIH DARI SATU','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(747,'PENGISIAN CAVUM PULPA','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(748,'TUMPATAN KLS 1 (KECIL), III DAN V GLASS LONOMER','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(749,'TUMPATAN KLS 1 (BESAR), II GLASS LONOMER','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(750,'TUMPATAN KLS 1 (KECIL), II (KECIL) III, IV DAN V K','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(751,'TUMPATAN KLS 1 (BESAR), ','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(752,'SCALLING PER RAHANG','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(753,'RESEMENTASI CROWN / BRIDGE','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(754,'PARTIAL IMPECTED','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(755,'DENTAL X-RAY PER FILEM','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(756,'REPOSISI TMJ','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(757,'SPLINTING PER RAHANG','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(758,'INSISI ABSES','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(759,'PASANG ETT/PASANG LEPAS ALAT BANTU INFASIF','','Aktif');
INSERT INTO dks_tindakan VALUES(760,'PASANG SYIRING PUMP/INFUS PUMP','','Aktif');
INSERT INTO dks_tindakan VALUES(761,'KELAS  VIP','','Aktif');
INSERT INTO dks_tindakan VALUES(762,'KELAS UTAMA','','Aktif');
INSERT INTO dks_tindakan VALUES(763,'KELAS 1','','Aktif');
INSERT INTO dks_tindakan VALUES(764,'KELAS 2','','Aktif');
INSERT INTO dks_tindakan VALUES(765,'KELAS 3','','Aktif');
INSERT INTO dks_tindakan VALUES(766,'KELAS VIP','','Aktif');
INSERT INTO dks_tindakan VALUES(767,'KANTONG DARAH (PMI)','KTG','Aktif');
INSERT INTO dks_tindakan VALUES(768,'USG DENGAN PRINT TIAP GAMBAR','LBR','Aktif');
INSERT INTO dks_tindakan VALUES(769,'USG TANPA PRINT GAMBAR (MONITOR)','','Aktif');
INSERT INTO dks_tindakan VALUES(770,'FOTO FILM KECIL 14/24 24/30','LBR','Aktif');
INSERT INTO dks_tindakan VALUES(771,'FOTO FILM BESAR 30/40 35/43','LBR','Aktif');
INSERT INTO dks_tindakan VALUES(772,'ADMINISTRASI PASIEN BARU ','','Aktif');
INSERT INTO dks_tindakan VALUES(773,'KARTU PASIEN BARU ((UMUM)','','Aktif');
INSERT INTO dks_tindakan VALUES(774,'KARTU PASIEN BARU (GAKIN)','','Aktif');
INSERT INTO dks_tindakan VALUES(775,'PASANG/LEPAS CHATETER ','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(776,'SKS DENGAN PASIEN MATA,INTERNA,THT','','Aktif');
INSERT INTO dks_tindakan VALUES(777,'PASANG/LEPAS OXYMETRI','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(778,'SITUBONDO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(779,'BONDOWOSO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(780,'BANYUWANGI','KM','Aktif');
INSERT INTO dks_tindakan VALUES(781,'JEMBER','KM','Aktif');
INSERT INTO dks_tindakan VALUES(782,'GENTENG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(783,'KRAKSAAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(784,'PROBOLINGGO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(785,'LUMAJANG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(786,'PASURUAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(787,'BANGIL','KM','Aktif');
INSERT INTO dks_tindakan VALUES(788,'SIDOARJO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(789,'MOJOSARI','KM','Aktif');
INSERT INTO dks_tindakan VALUES(790,'SURABAYA','KM','Aktif');
INSERT INTO dks_tindakan VALUES(791,'MALANG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(792,'BATU','KM','Aktif');
INSERT INTO dks_tindakan VALUES(793,'GRESIK','KM','Aktif');
INSERT INTO dks_tindakan VALUES(794,'MOJOKERTO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(795,'KEPANJEN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(796,'BANGKALAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(797,'LAMONGAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(798,'JOMBANG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(799,'SAMPANG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(800,'BLITAR','KM','Aktif');
INSERT INTO dks_tindakan VALUES(801,'NGANJUK','KM','Aktif');
INSERT INTO dks_tindakan VALUES(802,'KEDIRI','KM','Aktif');
INSERT INTO dks_tindakan VALUES(803,'TUBAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(804,'BOJONEGORO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(805,'PAMEKASAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(806,'TULUNG AGUNG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(807,'MADIUN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(808,'TRENGGALEK','KM','Aktif');
INSERT INTO dks_tindakan VALUES(809,'MAGETAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(810,'NGAWI','KM','Aktif');
INSERT INTO dks_tindakan VALUES(811,'SUMENEP','KM','Aktif');
INSERT INTO dks_tindakan VALUES(812,'PONOROGO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(813,'PACITAN','KM','Aktif');
INSERT INTO dks_tindakan VALUES(814,'SOLO','KM','Aktif');
INSERT INTO dks_tindakan VALUES(815,'YOGYAKARTA','KM','Aktif');
INSERT INTO dks_tindakan VALUES(816,'SEMARANG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(817,'BANDUNG','KM','Aktif');
INSERT INTO dks_tindakan VALUES(818,'JAKARTA','KM','Aktif');
INSERT INTO dks_tindakan VALUES(819,'SINGARAJA','KM','Aktif');
INSERT INTO dks_tindakan VALUES(820,'DENPASAR','KM','Aktif');
INSERT INTO dks_tindakan VALUES(821,'MATARAM','KM','Aktif');
INSERT INTO dks_tindakan VALUES(822,'NOJOKERTO','','Aktif');
INSERT INTO dks_tindakan VALUES(823,'ASEMBAGUS ','','Aktif');
INSERT INTO dks_tindakan VALUES(824,'ASEMBAGUS  ( T MAX )','','Aktif');
INSERT INTO dks_tindakan VALUES(825,'JANGKAR','','Aktif');
INSERT INTO dks_tindakan VALUES(826,'JANGKAR (T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(827,'BANYUPUTIH','','Aktif');
INSERT INTO dks_tindakan VALUES(828,'BANYUPUTIH (T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(829,'WONOREJO','','Aktif');
INSERT INTO dks_tindakan VALUES(830,'ARJASA','','Aktif');
INSERT INTO dks_tindakan VALUES(831,'ARJASA (T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(832,'KAPONGAN','','Aktif');
INSERT INTO dks_tindakan VALUES(833,'KLAMPOKAN','','Aktif');
INSERT INTO dks_tindakan VALUES(834,'PANJI','','Aktif');
INSERT INTO dks_tindakan VALUES(835,'MANGARAN','','Aktif');
INSERT INTO dks_tindakan VALUES(836,'PANARUKAN','','Aktif');
INSERT INTO dks_tindakan VALUES(837,'KENDIT','','Aktif');
INSERT INTO dks_tindakan VALUES(838,'KENDIT (T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(839,'BUNGATAN','','Aktif');
INSERT INTO dks_tindakan VALUES(840,'BUNGATAN (T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(841,'MLANDINGAN','','Aktif');
INSERT INTO dks_tindakan VALUES(842,'MLANDINGAN ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(843,'SUBOH ','','Aktif');
INSERT INTO dks_tindakan VALUES(844,'SUBOH ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(845,'BESUKI','','Aktif');
INSERT INTO dks_tindakan VALUES(846,'JATIBANTENG','','Aktif');
INSERT INTO dks_tindakan VALUES(847,'SUMBERMALANG','','Aktif');
INSERT INTO dks_tindakan VALUES(848,'SUMBERMALANG ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(849,'BANYUGLUGUR','','Aktif');
INSERT INTO dks_tindakan VALUES(850,'BANYUGLUGUR ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(851,'ASEMBAGUS ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(852,'JANGKAR ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(853,'BANYUPUTIH ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(854,'ARJASA ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(855,'KENDIT ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(856,'BUNGATAN ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(857,'SUMBER MALANG ( T MAX)','','Aktif');
INSERT INTO dks_tindakan VALUES(858,'RAPID TES ANTIGEN','','Aktif');
INSERT INTO dks_tindakan VALUES(859,'STERILISASI TIAP SET ALAT ','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(860,'INJEKSI OBAT (MAX3)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(861,'RAWAT LUKA RINGAN (<10CM)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(862,'RAWAT LUKA SEDANG(10-20CM)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(863,'RAWAT LUKA (>20CM)','KALI','Aktif');
INSERT INTO dks_tindakan VALUES(864,'PT','','Aktif');
INSERT INTO dks_tindakan VALUES(865,'APTT','','Aktif');
INSERT INTO dks_tindakan VALUES(866,'RAPID TES ANTIGEN MEI','','Aktif');
INSERT INTO dks_tindakan VALUES(867,'Sampah Medis','kg','Aktif');
INSERT INTO dks_tindakan VALUES(868,'Rapid Tes Antigen Baru','','Aktif');